project:
  title: "Method Package"
  type: website
  output-dir: _output
  render:
    - method_package.qmd
    - auxilary/introduction_to_rstudio_for_accfin.qmd
    - slides/slides1.qmd
    - slides/slides2.qmd
    - slides/slides3.qmd
    - slides/slides4.qmd
    - slides/slides5.qmd
    - freaky_friday/index.qmd
    - freaky_friday/download_linking.qmd
    - freaky_friday/linking.qmd
    - freaky_friday/download_data.qmd
    - freaky_friday/download_stocks.qmd
    - freaky_friday/abnormal_returns.qmd
    - freaky_friday/descriptive.qmd
    - freaky_friday/regressions.qmd
    - freaky_friday/assignment.qmd
    - machine_learning/*.qmd

website:
  page-navigation: true
  sidebar:
    style: docked
    search: true
    collapse-level: 1
    contents:
      - section: "Introduction"
        contents:
        - method_package.qmd
        - auxilary/introduction_to_rstudio_for_accfin.qmd
      - section: "Slides"
        contents:
        - slides/slides1.qmd
        - slides/slides2.qmd
        - slides/slides3.qmd
        - slides/slides4.qmd
        - slides/slides5.qmd
      - section: "Friday Earnings Announcements"
        contents:
        - freaky_friday/index.qmd
        - freaky_friday/download_linking.qmd
        - freaky_friday/linking.qmd
        - freaky_friday/download_data.qmd
        - freaky_friday/download_stocks.qmd
        - freaky_friday/abnormal_returns.qmd
        - freaky_friday/descriptive.qmd
        - freaky_friday/regressions.qmd
        - freaky_friday/assignment.qmd
      - section: "Machine Learning"
        contents:
        - machine_learning/predictions.qmd
        - machine_learning/theory.qmd
        - machine_learning/application.qmd

bibliography: citations.bib
author: "Stijn Masschelein"



