---
author: "Stijn Masschelein"
title: "Fast (?) Baker et al. simulation"
---

# R Setup

```{r}
library(here)
library(tidyverse)
library(collapse)
library(data.table)
library(RPostgres)
library(fixest)
i_am("auxilary/baker_simulation.Rmd")
run_wrds <- FALSE
file <- here("data", "roas.RDS")
```

# WRDS

```{r wrds_connection, eval = run_wrds}
wrds <- dbConnect(Postgres(),
                  host='wrds-pgdata.wharton.upenn.edu',
                  port=9737,
                  dbname='wrds',
                  user='stimas',
                  sslmode='require')
```

See [Compustat/WRDS](https://wrds-www.wharton.upenn.edu/pages/support/research-wrds/research-guides/procedures-using-fama-and-french-48-industry-classification/)

```{r wrds_query, eval = run_wrds}
sql1 <- "SELECT fyear, gvkey, oibdp, at, sich
       FROM COMP.FUNDA
       WHERE fyear > 1978 AND fyear < 2016 AND indfmt = 'INDL' AND datafmt = 'STD'
       AND popsrc = 'D' AND consol = 'C' AND fic = 'USA'"
res <- dbSendQuery(wrds, sql1)
dt <- as_tibble(dbFetch(res)) %>%
  rename_all(tolower)
dbClearResult(res)
roas <- dt %>%
  rename(year = fyear, firm = gvkey) %>%
  filter(!is.na(year), !is.na(at), !is.na(oibdp), at > 0) %>%
  group_by(firm) %>% arrange(year) %>%
  mutate(roa = oibdp / lag(at)) %>%
  ungroup() %>%
  select(year, firm, roa, sich) %>%
  filter(!is.na(roa), year > 1979)
glimpse(roas)
```

```{r, eval = run_wrds}
sql2 <- "SELECT gvkey, incorp, sic FROM crsp.comphead"
res <- dbSendQuery(wrds, sql2)
dt2 <- as_tibble(dbFetch(res)) %>%
  rename_all(tolower)
dbClearResult(res)
roas <- rename(dt2, firm = gvkey) %>%
  filter(!is.na(incorp) & incorp %in% state.abb) %>%
  right_join(roas) %>%
  mutate(sich = coalesce(sich, sic)) %>%
  filter(!sich %in% c(6000:6999)) %>%
  glimpse()
```

```{r, eval = run_wrds}
roas <- roas %>%
  group_by(firm) %>%
  add_tally() %>%
  filter(n >= 5) %>%
  ungroup()
glimpse(roas)

# winsorize ROA at 99, and censor at -1
wins <- function(x) {
  # winsorize and return
  case_when(
    is.na(x) ~ NA_real_,
    x < -1 ~ -1,
    x > quantile(x, 0.99, na.rm = TRUE) ~ quantile(x, 0.99, na.rm = TRUE),
    TRUE ~ x
  )
}

# winsorize ROA by year
roas <- roas %>%
  group_by(year) %>%
  mutate(roa = wins(roa)) %>%
  arrange(firm, year) %>%
  ungroup()
```

```{r, eval = run_wrds}
saveRDS(roas, file)
```


# Create Data

The deletion of the tails is just to get to a reasonable standard deviation.

```{r}
roas <- readRDS(file) 
mtime <- file.info((file))$mtime
```

The data was last modified on `r mtime`

# Decomposition

```{r}
decomp_dplyr <- function(){
roas %>%
  group_by(year) %>%
  mutate(fey = mean(roa)) %>%
  group_by(firm) %>%
  mutate(fef = mean(roa)) %>%
  ungroup() %>%
  mutate(residual = roa - fey - fef)
}
decomp_fast <- function(){
  roas %>%
    fgroup_by(year) %>%
    fmutate(fey = fmean(roa)) %>%
    fgroup_by(firm) %>%
    fmutate(fef = fmean(roa)) %>%
    fungroup() %>%
    fmutate(residual = roa - fef - fey) 
}
decomp_fixest <- function(){
  mod <- feols(roa ~ 1 | firm + year, data = roas)
  firm_fes <- fixef(mod)$firm
  year_fes <- fixef(mod)$year
  return(list(ff = firm_fes, fy = year_fes, resid = resid(mod)))
}
microbenchmark::microbenchmark(dplyr = decomp_dplyr(),
                               collapse = decomp_fast(),
                               fixest = decomp_fixest(),
                  times = 100)
decomp <- decomp_fixest()
glimpse(decomp)
```

Holy smokes!

# Sampling

```{r, sampling-preparation}
n <- fnrow(roas)
sigma_roa <- sd(roas$roa)
observations <- setDT(fselect(roas, year, firm))
observations[, firm := as.numeric(firm)]
firms <- data.table(firm = as.numeric(names(decomp$ff)), fef = decomp$ff)
years <- data.table(year = as.numeric(names(decomp$fy)), fey = decomp$fy)
residuals <- decomp$res
treatment_groups <- c(1989, 1998, 2007)
treatment_effects <- c(.05, .03, .01)
state_treatments <- sample(1:3, 50, TRUE)
```

The next step is to allow for different treatment effects

```{r}
#nfirm <- 1000
new_sample <- function(){
  sample_firms <- firms[, fef := sample(fef, .N, TRUE)]
  sample_years <- years[, fey := sample(fey, .N, TRUE)]
  sample_firms[, state := sample(1:50, .N, TRUE)]
  sample_firms[, state_treatment := state_treatments[state]]
  sample_firms[, treatment_group := treatment_groups[state_treatment]]
  sample_firms[, treatment_effect := treatment_effects[state_treatment]]
  new <- observations[
    sample_firms, on = .(firm = firm)][
    sample_years, on = .(year = year)]
  new[, treatment := treatment_effect * sigma_roa * pmax(year - treatment_group + 1, 0)]
  new[, roa := treatment + fef + fey + sample(residuals, .N, TRUE)]
  new[, rel_year := year - treatment_group]
  return(as.data.table(new))
}
new_sample()
microbenchmark::microbenchmark(sample = new_sample(), times = 100)
```

TODO

[] Read up on `.SD` function.

# Analyse

## Two-way Fixed Effects

```{r twoway}
new <- new_sample()
twoway <- feols(roa ~ ifelse(year >= treatment_group, 1, 0)| year + firm,
                cluster = "state", data = new)
etable(twoway)
coefficients(twoway)
```

## Sun and Abraham

See [Andrew Baker's Github](https://github.com/andrewchbaker/JFE_DID/blob/main/Code/1e.%20Alternative%20Event%20Study%20Estimators.R)

```{r sun}
max_rel_year <- 5
sa_new <- new_sample() %>%
  filter(year < treatment_group | rel_year <= max_rel_year) %>%
  filter(year < 2007)
sun_ab <- feols(roa ~ 1 + sunab(treatment_group, year)
                | firm + year, sa_new)
etable(sun_ab)
summary(sun_ab, agg = "ATT")
ATT <- coeftable(summary(sun_ab, agg = "ATT"))[1,1]
print(ATT)
```

## True ATT

```{r att}
true_att <- (max_rel_year + 2)/2 * sigma_roa * treatment_effects
collap(new[rel_year %in% 0:5], treatment ~ rel_year + treatment_group) %>%
  collap(treatment ~ treatment_group)
print(true_att)
```

# Simulation

```{r simulation}
nsim <- 500
simulate <- function(sim = 1){
  new <- new_sample()
  twoway <- feols(roa ~ ifelse(year >= treatment_group, 1, 0)
                  | year + firm, data = new)
  twoway_coef = coefficients(twoway)[1]
  sa_new <- new[(year < treatment_group | rel_year <= 5) & year < 2007]
  sun_ab  <- feols(roa ~ 1 + sunab(treatment_group, year)
                   | firm + year, sa_new)
  sun_ab_att <- coeftable(summary(sun_ab, agg = "ATT"))[1,1]
  results <- c(twoway_coef, sun_ab_att)
  names(results) <- c("twoway", "sun_abraham")
  return(results)
}
simulate()
estimates <- parallel::mclapply(1:nsim, FUN = simulate, mc.cores = 4L) %>%
  bind_rows()
summary(estimates)
hist(estimates$twoway, breaks = nsim/20)
hist(estimates$sun_abraham, breaks = nsim/20)
abline(v = mean(true_att[1:2]), col = "blue")
plot(estimates$twoway, estimates$sun_abraham)
```


